Task - 1
Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [23]:
import pandas as pd
from numpy import random
x = random.randint(100, size=(4, 4))
df = pd.DataFrame(x)
df

    0   1   2   3
0  74  58  29  52
1  56  34  87  72
2  65  13  65  76
3  45  91  77  87

Task - 2
Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [24]:
df.rename(columns = {0:"Random Value 1",1:"Random Value 2",2:"Random Value 3",3:"Random Value 4"},inplace = True)
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0              74              58              29              52
1              56              34              87              72
2              65              13              65              76
3              45              91              77              87

Task - 3
Find the descriptive statistics of the 'df' dataframe.

In [25]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean        60.000000       49.000000       64.500000       71.750000
std         12.409674       33.496268       25.317978       14.614491
min         45.000000       13.000000       29.000000       52.000000
25%         53.250000       28.750000       56.000000       67.000000
50%         60.500000       46.000000       71.000000       74.000000
75%         67.250000       66.250000       79.500000       78.750000
max         74.000000       91.000000       87.000000       87.000000

Task - 4
Check for the null values in 'df' and find the data type of the columns.

In [26]:
df.isnull().any()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      int64
 1   Random Value 2  4 non-null      int64
 2   Random Value 3  4 non-null      int64
 3   Random Value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

Task - 5
Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [27]:
df.loc[0:3,"Random Value 2":"Random Value 3"]

   Random Value 2  Random Value 3
0              58              29
1              34              87
2              13              65
3              91              77

In [28]:
df.iloc[0:4,1:3]

   Random Value 2  Random Value 3
0              58              29
1              34              87
2              13              65
3              91              77